CREATE TABLESPACE olgo_tableSpace DATAFILE 'D:\app\olgo\oradata\orcl\olgo_basecourse.dbf' SIZE 100M REUSE AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;

 

CREATE USER olgo IDENTIFIED BY nba777  DEFAULT TABLESPACE olgo_tableSpace;

GRANT UNLIMITED TABLESPACE TO olgo;

GRANT CREATE SESSION   TO olgo;

GRANT ALTER  SESSION   TO olgo;

GRANT CREATE TABLE     TO olgo;

GRANT CREATE PROCEDURE TO olgo;

GRANT CREATE VIEW      TO olgo;

GRANT CREATE SEQUENCE  TO olgo;

GRANT CREATE TRIGGER   TO olgo;

GRANT CREATE TYPE      TO olgo;

GRANT CREATE SYNONYM   TO olgo;

GRANT CREATE JOB       TO olgo;

GRANT CREATE MATERIALIZED VIEW TO olgo;

GRANT SELECT ANY DICTIONARY TO olgo;

GRANT READ, WRITE ON DIRECTORY DATA_PUMP_DIR TO olgo;

GRANT EXECUTE ON SYS.DBMS_LOCK   TO olgo;

GRANT EXECUTE ON SYS.DBMS_LOB    TO olgo;

GRANT EXECUTE ON SYS.DBMS_CRYPTO TO olgo;

GRANT EXECUTE ON SYS.DBMS_TRANSACTION TO olgo;

GRANT EXECUTE ON SYS.DBMS_SCHEDULER TO olgo;

GRANT EXECUTE ON SYS.DBMS_REPUTIL TO olgo;

GRANT EXECUTE ON SYS.DBMS_AQADM TO olgo;

GRANT EXECUTE ON SYS.DBMS_AQIN  TO olgo;

GRANT EXECUTE ON SYS.DBMS_AQ    TO olgo;

GRANT EXECUTE ON CTXSYS.CTX_CLS TO olgo;

GRANT EXECUTE ON CTXSYS.CTX_DDL TO olgo;
